import VocaSetInfo from "../types/VocaSetInfo.ts";

export const mockVocaSets: VocaSetInfo[] = [
  {
    id: "2",
    title: "500 Essential Words for TOEFL - Intermediate English",
    qualification: "intermediate",
    topic: "Chemistry",
    author: "Jane Smith",
    takenNumber: "1.8m",
  },
  {
    id: "3",
    title: "300 Basic Words for TOEFL - Beginner English",
    qualification: "beginner",
    topic: "General Science",
    author: "Alex Johnson",
    takenNumber: "1.2m",
  },
  {
    id: "4",
    title: "600 Advanced Words for TOEFL - Advanced English",
    qualification: "advanced",
    topic: "Physics",
    author: "Emily Davis",
    takenNumber: "3.5m",
    image:
      "https://www.voca.vn/assets/file_upload/images/english-words-for-advanced-1621595875.jpg",
  },
  {
    id: "5",
    title: "450 Key Vocabulary Words for TOEFL - Intermediate English",
    qualification: "intermediate",
    topic: "Economics",
    author: "Michael Brown",
    takenNumber: "2.3m",
  },
  {
    id: "6",
    title: "350 TOEFL Words - Beginner Level",
    qualification: "beginner",
    topic: "Mathematics",
    author: "Olivia Green",
    takenNumber: "1.0m",
    image:
      "https://www.voca.vn/assets/file_upload/images/english-words-for-starter-1621594978.jpg",
  },
  {
    id: "7",
    title: "Advanced Vocabulary for TOEFL - 700 Words",
    qualification: "advanced",
    topic: "Literature",
    author: "Lucas White",
    takenNumber: "3.8m",
  },
  {
    id: "8",
    title: "Intermediate Vocabulary for TOEFL - 400 Words",
    qualification: "intermediate",
    topic: "History",
    author: "Sophia Black",
    takenNumber: "2.0m",
    image:
      "https://www.voca.vn/assets/file_upload/images/english-words-for-pre-intermediate-1621595904.jpg",
  },
  {
    id: "9",
    title: "200 Foundation Words for TOEFL - Beginner",
    qualification: "beginner",
    topic: "Science",
    author: "James Lee",
    takenNumber: "900k",
    image:
      "https://www.voca.vn/assets/file_upload/images/3000-smart-words-1622106085.jpg",
  },
  {
    id: "10",
    title: "500 Advanced TOEFL Vocabulary - Expert Level",
    qualification: "advanced",
    topic: "Geography",
    author: "Isabella Scott",
    takenNumber: "2.9m",
    image:
      "https://www.voca.vn/assets/file_upload/images/1000-smart-words-in-topics-no1-avatar-1622106063.jpg",
  },
  {
    id: "11",
    title: "Core 450 Words for TOEFL - Intermediate",
    qualification: "intermediate",
    topic: "Business Studies",
    author: "Ethan Brown",
    takenNumber: "1.7m",
    image:
      "https://www.voca.vn/assets/file_upload/images/english-words-for-intermediate-1621595795.jpg",
  },
  {
    id: "12",
    title: "700 Comprehensive Words for TOEFL - Advanced",
    qualification: "advanced",
    topic: "Engineering",
    author: "Mia Wilson",
    takenNumber: "3.6m",
  },
  {
    id: "13",
    title: "Basic TOEFL Vocabulary - 250 Words",
    qualification: "beginner",
    topic: "Art",
    author: "David Johnson",
    takenNumber: "800k",
  },
  {
    id: "14",
    title: "Intermediate TOEFL Words - 350 Essential Vocabulary",
    qualification: "intermediate",
    topic: "Computer Science",
    author: "Emma Thompson",
    takenNumber: "1.5m",
    image:
      "https://www.voca.vn/assets/file_upload/images/english-words-for-upper-intermediate-1621595887.jpg",
  },
  {
    id: "15",
    title: "800 Words for TOEFL Mastery - Advanced Level",
    qualification: "advanced",
    topic: "Medicine",
    author: "Ava Martinez",
    takenNumber: "4.0m",
  },
];
