name: Build, Push Docker Image & Deploy on VPN via SSH

on:
  push:
    branches:
      - develop

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} --build-arg VITE_TINY_KEY=${{ secrets.VITE_TINY_KEY }} --build-arg VITE_CLOUDINARY_PRESET_NAME=${{ secrets.VITE_CLOUDINARY_PRESET_NAME }} --build-arg VITE_CLOUDINARY_CLOUD_NAME=${{ secrets.VITE_CLOUDINARY_CLOUD_NAME }} --build-arg VITE_GOOGLE_CLIENT_ID=224455832041-745s0jjjj1lglg40ccvcgvspisfka6ri.apps.googleusercontent.com -t dattrungnam510/engflashfe:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push dattrungnam510/engflashfe:latest

      - name: SSH into VPN server and deploy Docker image
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPN_SERVER_IP }}
          username: ${{ secrets.VPN_USERNAME }}
          password: ${{ secrets.VPN_PASSWORD }}
          port: 22
          script: |
            echo "SSH into VPN server"

            echo "Stopping and removing old containers..."
            docker ps -a -q --filter "ancestor=dattrungnam510/engflashfe:latest" | xargs -r docker stop
            docker ps -a -q --filter "ancestor=dattrungnam510/engflashfe:latest" | xargs -r docker rm -f

            echo "Removing old images..."
            docker images -q dattrungnam510/engflashfe:latest | xargs -r docker rmi -f

            echo "Starting the container with the new image..."
            docker-compose -f /home/engflash/docker-compose-fe.yml up -d
