export default interface VocaSet {
  id: string;
  name: string;
  author: string;
  level: string;
  takenStudents: number;
  lessons: number;
  image?: string;
}

export const mockVocaSets: VocaSet[] = [
  {
    id: "1",
    name: "Vocabulary Set 1",
    author: "EngFlash",
    level: "Beginner",
    takenStudents: 10,
    lessons: 10,
    image:
      "https://www.voca.vn/assets/file_upload/images/english-words-for-starter-1621594978.jpg",
  },
  {
    id: "2",
    name: "Vocabulary Set 2",
    author: "Adree",
    level: "Intermediate",
    takenStudents: 20,
    lessons: 20,
  },
  {
    id: "3",
    name: "Vocabulary Set 3",
    author: "LearnFast",
    level: "Advanced",
    takenStudents: 15,
    lessons: 25,
  },
  {
    id: "4",
    name: "Vocabulary Set 4",
    author: "EduMaster",
    level: "Beginner",
    takenStudents: 30,
    lessons: 12,
  },
  {
    id: "5",
    name: "Vocabulary Set 5",
    author: "VocabPro",
    level: "Intermediate",
    takenStudents: 40,
    lessons: 18,
  },
  {
    id: "6",
    name: "Vocabulary Set 6",
    author: "LinguaPlus",
    level: "Advanced",
    takenStudents: 25,
    lessons: 22,
  },
  {
    id: "7",
    name: "Vocabulary Set 7",
    author: "WordMaster",
    level: "Beginner",
    takenStudents: 5,
    lessons: 8,
  },
  {
    id: "8",
    name: "Vocabulary Set 8",
    author: "FlashLearn",
    level: "Intermediate",
    takenStudents: 60,
    lessons: 15,
  },
  {
    id: "9",
    name: "Vocabulary Set 9",
    author: "SpeedyWords",
    level: "Advanced",
    takenStudents: 12,
    lessons: 20,
  },
  {
    id: "10",
    name: "Vocabulary Set 10",
    author: "QuickStudy",
    level: "Beginner",
    takenStudents: 28,
    lessons: 10,
  },
  {
    id: "11",
    name: "Vocabulary Set 11",
    author: "BrightWords",
    level: "Intermediate",
    takenStudents: 22,
    lessons: 16,
  },
  {
    id: "12",
    name: "Vocabulary Set 12",
    author: "EasyVocab",
    level: "Beginner",
    takenStudents: 35,
    lessons: 14,
  },
  {
    id: "13",
    name: "Vocabulary Set 13",
    author: "ProLearner",
    level: "Advanced",
    takenStudents: 18,
    lessons: 26,
  },
  {
    id: "14",
    name: "Vocabulary Set 14",
    author: "SkillBoost",
    level: "Intermediate",
    takenStudents: 55,
    lessons: 18,
  },
  {
    id: "15",
    name: "Vocabulary Set 15",
    author: "WordWizard",
    level: "Beginner",
    takenStudents: 40,
    lessons: 9,
  },
  {
    id: "16",
    name: "Vocabulary Set 16",
    author: "LexiLearn",
    level: "Advanced",
    takenStudents: 20,
    lessons: 24,
  },
  {
    id: "17",
    name: "Vocabulary Set 17",
    author: "QuickWords",
    level: "Intermediate",
    takenStudents: 45,
    lessons: 19,
  },
  {
    id: "18",
    name: "Vocabulary Set 18",
    author: "LearnEasy",
    level: "Beginner",
    takenStudents: 32,
    lessons: 11,
  },
  {
    id: "19",
    name: "Vocabulary Set 19",
    author: "WordyWise",
    level: "Intermediate",
    takenStudents: 27,
    lessons: 13,
  },
  {
    id: "20",
    name: "Vocabulary Set 20",
    author: "SmartVocab",
    level: "Advanced",
    takenStudents: 14,
    lessons: 21,
  },
  {
    id: "21",
    name: "Vocabulary Set 21",
    author: "EngAce",
    level: "Beginner",
    takenStudents: 50,
    lessons: 12,
  },
  {
    id: "22",
    name: "Vocabulary Set 22",
    author: "StudyBuddy",
    level: "Intermediate",
    takenStudents: 33,
    lessons: 17,
  },
  {
    id: "23",
    name: "Vocabulary Set 23",
    author: "VocabKing",
    level: "Advanced",
    takenStudents: 19,
    lessons: 23,
  },
  {
    id: "24",
    name: "Vocabulary Set 24",
    author: "LinguaLab",
    level: "Beginner",
    takenStudents: 8,
    lessons: 10,
  },
];
